name: daily_quotation_app
description: >-
  Cross-platform Flutter app delivering daily inspirational quotes, wallpapers,
  and monetization-ready experiences.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  google_mobile_ads: ^4.0.0
  wallpaper_manager_flutter: ^1.0.4
  path_provider: ^2.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quotes/
